# Loops

In [1]:
from IPython.display import IFrame

# Display PDF with responsive width and height
IFrame("https://projector-video-pdf-converter.datacamp.com/799/chapter4.pdf", width="100%", height="600px")

### for loop

In [5]:
# for loop

fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam):
    print('index ' + str(index)+ ': '+ str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89


In [8]:
for c in 'family':
    print(c.capitalize())

F
A
M
I
L
Y


## iterating through dictionary

for this we can use the `items()` method of the dictionary object. This method returns a list of tuples where each tuple contains a key-value pair.

```python
d = {'a': 1, 'b': 2, 'c': 3}
for key, value in d.items():
    print(key, value)
```

In [4]:
world = { "afghanistan":30.55,
"albania":2.77,
"algeria":39.21 }
for k, v in world.items() :
    print(k + " -- " + str(v))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


## NumPy Array

### 1 Dimensional Array

In [7]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
# here at 1D we get back single array which we can iterate through staightforward
print(bmi)
for val in bmi :
    print(val)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


### 2D NumPy Arrays

In [8]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
# here we get 2arrays for 2D. so, for iterating, we can't directly access the innermost values
for val in meas :
    print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]
