# Loops

In [2]:
from IPython.display import IFrame

# Display PDF with responsive width and height
IFrame("https://projector-video-pdf-converter.datacamp.com/799/chapter4.pdf", width="100%", height="600px")

### for loop

In [3]:
# for loop

fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam):
    print('index ' + str(index)+ ': '+ str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89


In [4]:
for c in 'family':
    print(c.capitalize())

F
A
M
I
L
Y


## iterating through dictionary

for this we can use the `items()` method of the dictionary object. This method returns a list of tuples where each tuple contains a key-value pair.

```python
d = {'a': 1, 'b': 2, 'c': 3}
for key, value in d.items():
    print(key, value)
```

In [5]:
world = { "afghanistan":30.55,
"albania":2.77,
"algeria":39.21 }
for k, v in world.items() :
    print(k + " -- " + str(v))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


## NumPy Array

### 1 Dimensional Array

In [6]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
# here at 1D we get back single array which we can iterate through staightforward
print(bmi)
for val in bmi :
    print(val)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


### 2D NumPy Arrays

In [7]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
# here we get 2arrays for 2D. so, for iterating, we can't directly access the innermost values
for val in meas :
    print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [8]:
# for extracting the inner items of an 2D array, we can do following

import numpy as np
np_height = np.array([1.73, 1.54, 1.66, 1.56])
np_weight = np.array([65.4, 59.2, 56.6, 68.5])
meas = np.array([np_height, np_weight])
print(meas)
for val in np.nditer(meas):
    print(val)

[[ 1.73  1.54  1.66  1.56]
 [65.4  59.2  56.6  68.5 ]]
1.73
1.54
1.66
1.56
65.4
59.2
56.6
68.5


[![https://imgur.com/Ou0voyN.png](https://imgur.com/Ou0voyN.png)](https://imgur.com/Ou0voyN.png)

### Loop over NumPy array

If you're dealing with a 1D NumPy array, looping over all elements can be as simple as:

for x in my_array :
    ...

If you're dealing with a 2D NumPy array, it's more complicated. A 2D array is built up of multiple 1D arrays. To explicitly iterate over all separate elements of a multi-dimensional array, you'll need this syntax:

for x in np.nditer(my_array) :
    ...

Two NumPy arrays that you might recognize from the intro course are available in your Python session: np_height, a NumPy array containing the heights of Major League Baseball players, and np_baseball, a 2D NumPy array that contains both the heights (first column) and weights (second column) of those players.

In [9]:
# Import numpy as np
import numpy as np
np_baseball = meas
# For loop over np_height
for x in np_height :
    print(str(x) + ' inches')
# For loop over np_baseball
for x in np.nditer(np_baseball):
    print(str(x) )

1.73 inches
1.54 inches
1.66 inches
1.56 inches
1.73
1.54
1.66
1.56
65.4
59.2
56.6
68.5


### loop through pandas DataFrame



In [22]:
import pandas as pd
brics = pd.read_csv("./data/brics.csv", index_col = 0)
# brics
for lab,row in brics.iterrows():
    print('\n___________'+lab+'___________')
    print(row)


___________BR___________
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object

___________RU___________
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object

___________IN___________
country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object

___________CH___________
country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object

___________SA___________
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


### Selective print
- select only the rows that have a certain value in a certain column

In [26]:
import pandas as pd
brics = pd.read_csv("./data/brics.csv", index_col = 0)
for lab, row in brics.iterrows():
    print(lab + ": " + row["capital"])

    # here row['capital'] is the thing which is used to select a certain value from a row
    # refer to dictionary selection method

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


### Add column

Add a new column to the DataFrame
- method1: easy but not efficient

In [30]:
import pandas as pd
brics = pd.read_csv("./data/brics.csv", index_col = 0)
for lab, row in brics.iterrows() :
    # - Creating Series on every iteration
    brics.loc[lab, "name_length"] = len(row["country"])
    print(brics)

    # this method is not efficient as u can see, it is iteration the dataframe rows again and again until each row have the name_length value from each iteration

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          NaN
IN         India  New Delhi   3.286     1252.00          NaN
CH         China    Beijing   9.597     1357.00          NaN
SA  South Africa   Pretoria   1.221       52.98          NaN
         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          NaN
CH         China    Beijing   9.597     1357.00          NaN
SA  South Africa   Pretoria   1.221       52.98          NaN
         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          5.0
CH         China    Beij

- method2: efficient but bit complex

In [28]:
import pandas as pd
brics = pd.read_csv("./data/brics.csv", index_col = 0)
brics["name_length"] = brics["country"].apply(len)
print(brics)

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40            6
RU        Russia     Moscow  17.100      143.50            6
IN         India  New Delhi   3.286     1252.00            5
CH         China    Beijing   9.597     1357.00            5
SA  South Africa   Pretoria   1.221       52.98           12


### more examples for adding coulumn

- Add column (2)

Using iterrows() to iterate over every observation of a Pandas DataFrame is easy to understand, but not very efficient. On every iteration, you're creating a new Pandas Series.

If you want to add a column to a DataFrame by calling a function on another column, the iterrows() method in combination with a for loop is not the preferred way to go. Instead, you'll want to use apply().

Compare the iterrows() version with the apply() version to get the same result in the brics DataFrame:

for lab, row in brics.iterrows() :
    brics.loc[lab, "name_length"] = len(row["country"])

brics["name_length"] = brics["country"].apply(len)

We can do a similar thing to call the upper() method on every name in the country column. However, upper() is a method, so we'll need a slightly different approach:


In [2]:
# Import cars data
import pandas as pd
cars = pd.read_csv('./data/cars.csv', index_col = 0)

# Use .apply(str.upper)
for lab, row in cars.iterrows() :
    cars.loc[lab, "COUNTRY"] = row["country"].upper()

cars

cars_per_cap        country  drives_right        COUNTRY
US            809  United States          True  UNITED STATES
AUS           731      Australia         False      AUSTRALIA
JAP           588          Japan         False          JAPAN
IN             18          India         False          INDIA
RU            200         Russia          True         RUSSIA
MOR            70        Morocco          True        MOROCCO
EG             45          Egypt          True          EGYPT

In [4]:
# Import cars data
import pandas as pd
cars = pd.read_csv('./data/cars.csv', index_col = 0)

# Use .apply(str.upper)
cars["COUNTRY"] = cars["country"].apply(str.upper)
cars

cars_per_cap        country  drives_right        COUNTRY
US            809  United States          True  UNITED STATES
AUS           731      Australia         False      AUSTRALIA
JAP           588          Japan         False          JAPAN
IN             18          India         False          INDIA
RU            200         Russia          True         RUSSIA
MOR            70        Morocco          True        MOROCCO
EG             45          Egypt          True          EGYPT